import { createApp } from 'vue';
import App from './App.vue';

const app = createApp(App);
app.mount('#app');

// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
// IF YOU CAN READ THIS, YOU HAVE DOWNLOADED THE CORRECT VERSION FOR THE LECTURE
   